python train.py \
    --network hypernet \
    --batch-size 16 \
    --data-shape 448 \
    --optimizer-name nadam \
    --freeze '' \
    --pretrained none \
    --epoch 1000 \
    --lr 0.001 \
    --frequent 20 \
    --gpus 0
