python train.py \
    --network hypernet \
    --batch-size 32 \
    --data-shape 448 \
    --optimizer-name sgd \
    --freeze '' \
    --pretrained ./model/ssd_hypernet_448 \
    --epoch 1000 \
    --lr 2e-03 \
    --lr-steps 3,4,5,6 \
    --frequent 50 \
    --gpus 0,1
